name: mini_asr
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - torch==1.6.0
    - torchaudio>=0.6.0
    - h5py
    - librosa
    - numpy
    - protobuf
    - scipy
    - scikit-learn
    - tqdm
    - SoundFile
    - matplotlib
    - kaldi_io
    - yamlargparse